language: go

variables:
  GOPROXY: "off"

go:
  - "1.15.x" # must be quoted in order to work correctly
  - master

before_install:
  - go get -t -v ./...
  - make binaries

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)